---
general:
  healthcheckEvery: 2s
  httpClientTimeout: 5s
  refreshDashboardEvery: 5s
groups:
  - name: Frontend (us-east-1)
    nodes:
      - name: front-1 (current)
        endpoint: https://www.example.com/
        type: http_check
        parameters:
          expectedPattern: Example
          basicAuthUsername: username
          basicAuthPassword: password
      - name: front-2a (deprecated)
        endpoint: https://www.example.com/
        expectedPattern: Example
      - name: front-2b (deprecated)
        endpoint: https://www.example.com/
        expectedPattern: WillNotFindThis
      - name: front-2c (current)
        endpoint: https://www.example.com/
        parameters:
          expectedPattern: WillNotFindThis
      - name: front-3
        type: sample_check
        parameters:
          greenDay: 21
  - name: Middleware (us-west-2)
    nodes:
      - name: middleware-1 master host
        endpoint: https://www.example.com/
      - name: localhost
        endpoint: 127.0.0.1
        type: ping_check
      - name: Wirtualna Polska
        endpoint: wp.pl
        type: ping_check
      - name: middleware-4
        endpoint: 874397492374qwerty.pl
        type: ping_check
      - name: middleware-5
        endpoint: https://www.example.com/
  - name: Backend (us-west-2)
    nodes:
      - name: backend-1 master host
        endpoint: google.com:443
        type: tls_check
      - name: backend-2
        endpoint: https://1234567890.example.com/
      - name: backend-3
        endpoint: https://www.example.com/
